
/****** Object:  Table [dbo].[API_Transfer_TXN]    Script Date: 12/24/2014 02:49:53 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[API_Transfer_TXN](
	[sno] [int] IDENTITY(1,1) NOT NULL,
	[Tranno] [int] NOT NULL,
	[isTransfer] [char](1) NULL,
 CONSTRAINT [PK_API_Transfer_TXN] PRIMARY KEY CLUSTERED 
(
	[sno] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


