/****** Object:  StoredProcedure [dbo].[spa_Check_IntegrationTXN]    Script Date: 12/21/2014 14:02:38 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[spa_Check_IntegrationTXN]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[spa_Check_IntegrationTXN]
GO

/****** Object:  StoredProcedure [dbo].[spa_Check_IntegrationTXN]    Script Date: 12/21/2014 14:02:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

      
CREATE PROC [dbo].[spa_Check_IntegrationTXN]      
		@PARAM_PARENT_NODE VARCHAR(100)=NULL,
		@PARAM_CHILD_NODE VARCHAR(100)=NULL,
		@xmlValue xml    
as      
              
DECLARE @idoc INT                
DECLARE @doc  VARCHAR(max),@XQUERY VARCHAR(200)    

SET @XQUERY = '/'+ @PARAM_PARENT_NODE +'/'+ @PARAM_CHILD_NODE 

EXEC sp_xml_preparedocument @idoc OUTPUT,@xmlValue      
SELECT * INTO #temp_transaction          
     FROM   OPENXML(@idoc, @XQUERY ,2)           
            WITH (         
            StatusMsg varchar(50),    
    MESSAGE VARCHAR(100),    
 TotalDay varchar(50),      
 LinkSrvInfo varchar(100),      
 session_id varchar(100),      
      Tranno varchar(100) ,      
      refno varchar(100),      
      agentid varchar(100),      
      agentname varchar(100),      
      Branch_code varchar(100),      
      Branch varchar(100),      
      CustomerId varchar(100),      
      SenderName varchar(100),      
      SenderAddress varchar(100),      
      SenderPhoneno varchar(100),      
      senderFax varchar(100),      
      SenderCity varchar(100),      
      SenderCountry varchar(100),      
      SenderEmail varchar(100),      
      SenderCompany varchar(100),      
      senderPassport varchar(100),      
      senderVisa varchar(100),      
      ReceiverName varchar(100),      
      ReceiverAddress varchar(100),      
      ReceiverPhone varchar(100),      
      ReceiverFax varchar(100),      
      ReceiverCity varchar(100),      
      ReceiverCountry varchar(100),      
      ReceiverEMail varchar(100),      
      ReceiverIDDescription varchar(100),      
      ReceiverID varchar(100),      
      DOT varchar(100),      
      DOtTime varchar(100),      
      paidAmt varchar(50),      
      paidCType varchar(100),      
      receiveAmt varchar(50),      
      receiveCType varchar(100),      
      ExchangeRate decimal,      
      Today_Dollar_rate decimal,      
      Dollar_Amt varchar(50),      
      SCharge varchar(50),      
      ReciverMessage varchar(100),      
      TestQuestion varchar(100),      
      TestAnswer varchar(100),      
      amtSenderType varchar(100),      
      SenderBankID varchar(100),      
      SenderBankName varchar(100),      
      SenderBankBranch varchar(100),      
      SenderBankVoucherNo varchar(100),      
      Amt_paid_date varchar(100),      
      paymentType varchar(100),      
      rBankID varchar(100),      
      rBankName varchar(100),      
      rBankBranch varchar(100),      
      rBankACNo varchar(100),      
      rBankAcType varchar(100),      
      otherCharge varchar(50),      
      TransStatus varchar(100),      
      status varchar(100),      
      SEmpID varchar(100),      
      bTno varchar(100),      
      imeCommission varchar(50),      
      bankCommission varchar(50),      
      TotalRoundAmt varchar(50),      
      TransferType varchar(100),      
      Draftno varchar(100),      
      ChalaniNo varchar(100),      
      paidBy varchar(100),      
      paidDate varchar(100),      
      paidTime varchar(100),      
      courierID varchar(100),      
      PODDate varchar(100),      
      senderCommission varchar(50),      
      receiverCommission varchar(50),      
      approve_by varchar(100),      
      receiveAgentID varchar(100),      
      send_mode varchar(10),      
      confirmDate varchar(100),      
      local_dot varchar(100),      
      lock_status varchar(100),      
      lock_dot varchar(100),      
      lock_by varchar(100),      
      sender_mobile varchar(100),      
      receiver_mobile varchar(100),      
      ip_address varchar(100),      
      test_TRN varchar(10),      
      paid_agent_code varchar(100),      
      ho_dollar_rate varchar(50),      
      request_for_new_account varchar(10),      
      digital_id_sender varchar(100),      
      digital_id_payout varchar(100),      
      agent_settlement_rate varchar(50),      
      agent_ex_gain varchar(50),      
      cancel_date varchar(100),      
      cancel_by varchar(100),      
      senderSalary varchar(100),      
      ReceiverRelation varchar(100),      
      fax_trans varchar(10),      
      SenderNativeCountry varchar(100),      
      agent_dollar_rate varchar(50),      
      bonus_amt varchar(50),      
      trans_mode varchar(10),      
      expected_payoutagentid varchar(100),      
      bonus_value_amount varchar(50),      
      bonus_type varchar(10),      
      bonus_on varchar(10),      
      ben_bank_id varchar(100),      
      ben_bank_name varchar(100),      
      paid_agent_id varchar(100),      
      send_sms varchar(10),      
      agent_receiverCommission varchar(50),      
      agent_receiverSCommission varchar(50),      
      door_to_door varchar(10),      
      customer_sno varchar(100),      
      paid_date_usd_rate varchar(50),      
      payout_fx_share varchar(50),      
      Head_fx_share varchar(50),      
      source_of_income varchar(100),      
      reason_for_remittance varchar(100),      
      isIRH_trn varchar(10),      
      ben_father_name varchar(100),      
      secret_question varchar(100),      
      secret_answer varchar(100),      
      receiverID_placeOfIssue varchar(100),      
      mileage_earn varchar(50),      
      tds_com_per varchar(50),      
      payout_settle_usd varchar(50),      
      transfer_ts varchar(100),      
      hide_admin varchar(10),      
      paid_beneficiary_ID_type varchar(100),      
      paid_beneficiary_ID_number varchar(100),      
      confirm_process_id varchar(100),      
      c2c_pin_no varchar(100),      
      ext_sCharge varchar(50),      
      tds_com_per_send varchar(50),      
      extBankCommission varchar(50),      
      id_type varchar(100),      
      chk_cancel_charge varchar(10),      
      compliance_flag varchar(10),      
      compliance_sys_msg varchar(100),      
      agent_receiverComm_Currency varchar(10),      
      ID_Issue_date varchar(100),      
      Date_of_Birth varchar(100),      
      HO_confirmDate varchar(100),      
      ofac_list varchar(10),      
      ofac_app_by varchar(100),      
      ofac_app_ts varchar(100),      
      ben_dob varchar(100),      
      is_downloaded varchar(10),      
      authorization_code varchar(100),      
      downloaded_by varchar(100),      
      downloaded_ts varchar(100)                    
            )           
 EXEC sp_xml_removedocument @idoc       
       
 select *from #temp_transaction      
       
 drop table #temp_transaction
GO


