INSERT INTO static_values(sno,static_value,static_data,[Description]) VALUES (	31,'Select',NULL,NULL)
INSERT INTO static_values(sno,static_value,static_data,[Description]) VALUES (31,'Worker','Worker','Worker')
INSERT INTO static_values(sno,static_value,static_data,[Description]) VALUES (31,'Clerk','Clerk','Clerk')
INSERT INTO static_values(sno,static_value,static_data,[Description]) VALUES (31,'Supervisor','Supervisor','Supervisor')
INSERT INTO static_values(sno,static_value,static_data,[Description]) VALUES (31,'Manager','Manager','Manager')
INSERT INTO static_values(sno,static_value,static_data,[Description]) VALUES (31,'Labor','Labor','Labor')
INSERT INTO static_values(sno,static_value,static_data,[Description]) VALUES (31,'Student','Student','Student')
INSERT INTO static_values(sno,static_value,static_data,[Description]) VALUES (31,'Director','Director','Director')
INSERT INTO static_values(sno,static_value,static_data,[Description]) VALUES (31,'Other','Other','Other')
