--DROP TABLE provider_list
--GO
CREATE TABLE [dbo].[MPOS_provider_list](
	[provider_id] [int] IDENTITY(1,1) NOT NULL,
	[provider_name] [varchar](100) NULL,
 CONSTRAINT [PK_provider_list] PRIMARY KEY CLUSTERED 
(
	[provider_id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


