ALTER TABLE moneySend ADD  sender_occupation VARCHAR(150)
ALTER TABLE cancelMoneySend ADD  sender_occupation VARCHAR(150)
ALTER TABLE delMoneysend ADD  sender_occupation VARCHAR(150)
ALTER TABLE moneysend_arch1 ADD  sender_occupation VARCHAR(150)
ALTER TABLE moneysend_arch1_audit ADD  sender_occupation VARCHAR(150)
ALTER TABLE moneysend_audit ADD  sender_occupation VARCHAR(150)
ALTER TABLE customerDetail ADD  sender_occupation VARCHAR(150)