CREATE TABLE [dbo].[c2c_error_codes](
	[sno] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[code] [varchar](50) NULL,
	[Description] [varchar](2000) NULL,
	[Retriable] [char](1) NULL,
 CONSTRAINT [PK_c2c_error_codes] PRIMARY KEY CLUSTERED 
(
	[sno] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF