DROP TABLE [dbo].[FTP_FeedBack_BDO]
GO
CREATE TABLE [dbo].[FTP_FeedBack_BDO]
    (
      [SNO] [INT] IDENTITY(1, 1) ,
      [C_TREFNO] [NVARCHAR](25) NULL ,
      [C_RMCODE] [NVARCHAR](12) NULL ,
      [C_BFCODE] [NVARCHAR](2)  NULL ,
      [C_REMARKS1] [NVARCHAR](50) NULL ,
      [C_TRTYPE] [NVARCHAR](12) NULL ,
      [C_REMARKS2] [NVARCHAR](50) NULL ,
      [C_STATUS] [NVARCHAR](15)  NULL ,
      [D_PAID] [DATETIME] NULL ,
      [D_PROCESS] [DATETIME] NULL ,
      [C_BF2RM1] [NVARCHAR](50)  NULL ,
      [C_BF2RM2] [NVARCHAR](50)  NULL ,
      [N_AMTPAID] [MONEY] NULL ,
      [N_REMAMTO] [MONEY] NULL ,
      [C_SENDER] [NVARCHAR](40) ,
      [C_BENEF] [NVARCHAR](40)  NULL ,
      [C_OUTCURR] [NVARCHAR](3) NULL ,
      [IMPORTED_DATE] [DATETIME] DEFAULT DBO.GETDATEHO(GETUTCDATE()) ,
      [PROCESS_ID] [NVARCHAR](200) NULL,
      [SYSTEM_STATUS] [NVARCHAR] (200) NULL
    )
ON  [PRIMARY]